# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-12-04 16:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('userName', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EndUserOrders',
            fields=[
                ('order', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('delivery_address', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='general', max_length=32)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('inventoryProductAmount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('logistics', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='费用')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=128)),
                ('productAmount', models.PositiveIntegerField(default=0, verbose_name='product_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('warehouseName', models.CharField(max_length=64)),
                ('warehouseLocation', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('customer', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.Customer')),
                ('customerUserName', models.CharField(default='customer', max_length=64)),
                ('customerPassword', models.CharField(default='666666', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EndUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.EndUser')),
                ('gender', models.BooleanField(default=True)),
                ('birth', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=512, null=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('logistics', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.Logistics')),
                ('currentPosition', models.CharField(max_length=256)),
                ('currentTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimateArrivalTime', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.EndUserOrders')),
                ('supplier', models.CharField(choices=[('WH', 'WAREHOUSE'), ('ETC', 'OTHERS')], default='WH', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product', models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.Product')),
                ('color', models.CharField(max_length=32)),
                ('style', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='customerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='store_owner', to='warehouse.Customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(to='warehouse.Store'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory_location', to='warehouse.Warehouse', to_field='warehouseLocation'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Product'),
        ),
        migrations.AddField(
            model_name='enduserorders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Product'),
        ),
        migrations.AddField(
            model_name='enduserorders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.EndUser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='employeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WarehouseOrders',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.Orders')),
                ('logistics', models.ManyToManyField(null=True, to='warehouse.Logistics')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='logistics',
            field=models.ManyToManyField(null=True, to='warehouse.Logistics'),
        ),
    ]
